const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { withExif } = require('./exif-fixture.cjs');
const root = path.resolve(__dirname, '..');
let app;
(async () => {
  const data = await fs.mkdtemp(path.join(os.tmpdir(), 'party-app-test-'));
  await fs.mkdir(path.join(root, 'artifacts'), { recursive: true });
  const launch = async mode => {
    app = await electron.launch({ args: [root, `--mode=${mode}`], env: { ...process.env, PARTY_TEST: '1', PARTY_DATA_DIR: data }, timeout: 30000 });
    const page = await app.firstWindow(); page.on('pageerror', e => console.error('Renderer error:', e.message)); await page.waitForSelector('h1'); return page;
  };
  const page = await launch('booth');
  const invitationTheme = await page.evaluate(() => ({ background: getComputedStyle(document.body).backgroundColor, primary: getComputedStyle(document.querySelector('button.primary')).backgroundColor, heading: getComputedStyle(document.querySelector('h1')).fontFamily }));
  assert.equal(invitationTheme.background, 'rgb(254, 254, 249)'); assert.equal(invitationTheme.primary, 'rgb(84, 119, 136)'); assert.match(invitationTheme.heading, /Bodoni|Iowan|Georgia/);
  await page.screenshot({ path: path.join(root, 'artifacts/frame-setup.png') });
  // Verify the SVG grade actually changes exported pixels, and CSS preview agrees.
  const gradedPixel = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = canvas.height = 40;
    const ctx = canvas.getContext('2d'); ctx.fillStyle = 'rgb(190,140,105)'; ctx.fillRect(0, 0, 40, 40);
    const output = document.createElement('canvas'); output.width = output.height = 40;
    const g = output.getContext('2d'); g.filter = 'url(#portra400)'; g.drawImage(canvas, 0, 0);
    const patch = document.createElement('div'); patch.id = 'grade-test'; patch.style.cssText = 'position:fixed;top:50px;left:50px;width:40px;height:40px;background:rgb(190,140,105);filter:url(#portra400);z-index:999'; document.body.append(patch);
    return Array.from(g.getImageData(20, 20, 1, 1).data);
  });
  assert.notDeepEqual(gradedPixel.slice(0, 3), [190, 140, 105]);
  const patch = await page.locator('#grade-test').screenshot();
  const previewPixel = await app.evaluate(({ nativeImage }, bytes) => {
    const image = nativeImage.createFromBuffer(Buffer.from(bytes)); const size = image.getSize(); const bitmap = image.toBitmap(); const offset = (Math.floor(size.height / 2) * size.width + Math.floor(size.width / 2)) * 4;
    return [bitmap[offset + 2], bitmap[offset + 1], bitmap[offset]];
  }, Array.from(patch));
  previewPixel.forEach((v, i) => assert.ok(Math.abs(v - gradedPixel[i]) <= 2, `Preview/export channel ${i}: ${v} vs ${gradedPixel[i]}`));
  await page.locator('#grade-test').evaluate(el => el.remove());
  await page.locator('#look').selectOption('portra');
  await page.locator('#connect').click();
  await page.waitForFunction(() => !document.querySelector('#capture').disabled, { timeout: 15000 });
  assert.equal(await page.locator('#live').evaluate(el => getComputedStyle(el).transform), 'none');
  await page.screenshot({ path: path.join(root, 'artifacts/frame-live.png') });
  await page.locator('#capture').click();
  await page.waitForFunction(() => document.querySelector('#countdown').textContent === '2', { timeout: 5000 });
  assert.equal(await page.locator('#lens-cue').isVisible(), true);
  assert.match(await page.locator('#rp-graded').evaluate(el => getComputedStyle(el).filter), /blur\(16px\)/);
  await page.screenshot({ path: path.join(root, 'artifacts/frame-lens-cue.png') });
  await page.waitForFunction(() => document.querySelector('#booth-message').textContent === 'Saved', { timeout: 15000 });
  assert.equal(await page.locator('#lens-cue').isHidden(), true);
  assert.equal(await page.locator('#sync-list .sync-row').count(), 1);
  assert.match(await page.locator('#sync-list').textContent(), /Photo.*Waiting for setup/s);
  assert.equal(await page.locator('#sync-list .sync-delete').count(), 1);
  const base = path.join(data, 'Booth captures'); const day = (await fs.readdir(base))[0]; const dir = path.join(base, day, (await fs.readdir(path.join(base, day)))[0]); const savedPhotos = { dir, files: await fs.readdir(dir), metadata: JSON.parse(await fs.readFile(path.join(dir, 'capture.json'), 'utf8')) };
  assert.ok(savedPhotos.files.includes('original.jpg')); assert.ok(savedPhotos.files.includes('print.jpg')); assert.ok(savedPhotos.files.includes('thumb.jpg')); assert.ok(savedPhotos.metadata.width > 0);
  assert.equal(savedPhotos.metadata.source, 'canon-rp-tether'); assert.equal(savedPhotos.metadata.model, 'Canon EOS RP');
  assert.equal(savedPhotos.metadata.mirrored, false);
  assert.equal(await page.locator('#review-photo').evaluate(el => getComputedStyle(el).transform), 'none');
  assert.equal(await page.locator('#mode-video').count(), 0); assert.equal(await page.locator('#microphone').count(), 0); assert.equal(await page.locator('#audio').count(), 0);
  // Countdown cancellation must not create an extra capture.
  await page.locator('#capture').click(); await page.waitForFunction(() => document.querySelector('#booth-message').textContent === 'Ready');
  await page.locator('#capture').click();
  await page.waitForFunction(() => document.querySelector('#capture').textContent === 'Cancel');
  await page.locator('#capture').click();
  assert.equal(await page.locator('#booth-message').textContent(), 'Cancelled');
  assert.equal((await fs.readdir(path.dirname(savedPhotos.dir))).length, 1);
  // An I/O error must keep the capture pending; retry must save it once.
  await app.evaluate(({ ipcMain }) => { const original = ipcMain._invokeHandlers.get('save-capture'); ipcMain.removeHandler('save-capture'); ipcMain.handle('save-capture', async (...args) => { ipcMain.removeHandler('save-capture'); ipcMain.handle('save-capture', original); throw new Error('Simulated disk write failure'); }); });
  await page.locator('#capture').click(); await page.waitForSelector('#retry:visible', { timeout: 15000 });
  assert.equal((await fs.readdir(path.dirname(savedPhotos.dir))).length, 1);
  await page.locator('#retry').click(); await page.waitForFunction(() => document.querySelector('#booth-message').textContent === 'Saved');
  assert.equal((await fs.readdir(path.dirname(savedPhotos.dir))).length, 2);
  await page.locator('#capture').click(); await page.waitForFunction(() => document.querySelector('#booth-message').textContent === 'Ready');
  await page.locator('#guest').click();
  await page.waitForFunction(() => document.body.classList.contains('guest'));
  const guestLayout = await page.evaluate(() => {
    const screen = document.querySelector('.booth-screen').getBoundingClientRect();
    const controls = getComputedStyle(document.querySelector('.booth-controls'));
    const message = getComputedStyle(document.querySelector('#booth-message'));
    const capture = document.querySelector('#capture').getBoundingClientRect();
    return { widthRatio: screen.width / innerWidth, heightRatio: screen.height / innerHeight, controlsPosition: controls.position, messageSize: parseFloat(message.fontSize), captureHeight: capture.height };
  });
  assert.ok(guestLayout.widthRatio >= .79 && guestLayout.widthRatio <= .89);
  assert.ok(guestLayout.heightRatio >= .98);
  assert.equal(guestLayout.controlsPosition, 'absolute');
  assert.ok(guestLayout.messageSize >= 20);
  assert.ok(guestLayout.captureHeight >= 60);
  assert.equal(await page.locator('#live-label').isHidden(), true);
  const guestStatusSize = await page.locator('#countdown').evaluate(el => { el.classList.add('developing'); const size = parseFloat(getComputedStyle(el).fontSize); el.classList.remove('developing'); return size; });
  assert.ok(guestStatusSize <= 24);
  assert.ok(parseFloat(await page.locator('.booth-controls').evaluate(el => getComputedStyle(el).bottom)) >= 58);
  await page.screenshot({ path: path.join(root, 'artifacts/frame-guest.png') });
  await page.locator('#viewfinder').click({ position: { x: 500, y: 400 } });
  await page.waitForFunction(() => document.querySelector('#booth-message').textContent === 'Saved', { timeout: 15000 });
  const capturesAfterAudio = await fs.readdir(path.dirname(savedPhotos.dir));
  const newest = capturesAfterAudio.sort().at(-1); const audioMeta = JSON.parse(await fs.readFile(path.join(path.dirname(savedPhotos.dir), newest, 'capture.json'), 'utf8'));
  assert.equal(audioMeta.kind, 'photo');
  await page.locator('#guest-exit').click(); await page.waitForFunction(() => !document.body.classList.contains('guest'));
  const clipBytes = await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 90;
    const context = canvas.getContext('2d'), stream = canvas.captureStream(15), chunks = [];
    const recorder = new MediaRecorder(stream, { mimeType: 'video/webm' });
    recorder.ondataavailable = event => { if (event.data.size) chunks.push(event.data); };
    const stopped = new Promise(resolve => recorder.onstop = resolve); recorder.start(50);
    for (let frame = 0; frame < 12; frame++) { context.fillStyle = frame % 2 ? '#547788' : '#fefef9'; context.fillRect(0, 0, 160, 90); await new Promise(resolve => setTimeout(resolve, 50)); }
    recorder.stop(); await stopped; stream.getTracks().forEach(track => track.stop());
    return Array.from(new Uint8Array(await new Blob(chunks, { type: 'video/webm' }).arrayBuffer()));
  });
  const clip = path.join(data, 'loop-test.webm'); await fs.writeFile(clip, Buffer.from(clipBytes));
  await page.locator('#disconnect').click(); await app.close(); app = null;
  const loop = await launch('loop');
  const annotated = path.join(data, 'portrait-with-exif.jpg'); await fs.writeFile(annotated, withExif(await fs.readFile(path.join(savedPhotos.dir, 'print.jpg'))));
  await loop.screenshot({ path: path.join(root, 'artifacts/loop-empty.png') });
  await app.evaluate(async ({ ipcMain, BrowserWindow }, files) => { const listener = ipcMain._invokeHandlers.get('test-import'); const win = BrowserWindow.getAllWindows()[0]; await listener({ sender: win.webContents }, files); }, [annotated, clip, annotated, annotated, clip, annotated]);
  await loop.reload(); await loop.waitForSelector('#playlist li[data-id]'); assert.equal(await loop.locator('#playlist li[data-id]').count(), 6);
  // Exercise the actual preparation UI without relying on a network service in tests.
  await fs.writeFile(path.join(data, 'Loop library', 'places.json'), JSON.stringify({ '55.950,-3.200': { placeName: 'Edinburgh, United Kingdom', provider: 'Apple' } }));
  await loop.locator('#lookup-places').click(); await loop.waitForFunction(() => document.querySelector('#place-progress').textContent.includes('1 locations saved'));
  await loop.locator('#seconds').fill('2'); await loop.locator('#seconds').dispatchEvent('change');
  assert.match(await loop.locator('#runtime').textContent(), /Estimated rotation · about/);
  await loop.locator('#check').click(); await loop.waitForFunction(() => document.querySelector('#check-result').textContent.startsWith('All 6'), { timeout: 30000 });
  await loop.evaluate(() => scrollTo(0, 0));
  await loop.screenshot({ path: path.join(root, 'artifacts/loop-loaded.png') });
  await loop.locator('#playback-layout').selectOption('grid');
  assert.equal(await loop.locator('#sound').isDisabled(), true);
  const gridWindowPromise = app.waitForEvent('window'); await loop.locator('#start').click(); const gridOutput = await gridWindowPromise;
  await gridOutput.waitForFunction(() => document.querySelectorAll('#stage.grid .grid-tile').length === 6 && [...document.querySelectorAll('.grid-tile')].every(tile => tile.firstElementChild?.classList.contains('visible')));
  assert.deepEqual(await gridOutput.locator('.grid-tile img,.grid-tile video').evaluateAll(elements => elements.map(element => element.style.objectFit)), Array(6).fill('contain'));
  await loop.locator('#pause').click(); await loop.waitForFunction(() => document.querySelector('#pause').textContent === 'Resume');
  await loop.locator('#fit').selectOption('cover');
  await gridOutput.waitForFunction(() => [...document.querySelectorAll('.grid-tile img,.grid-tile video')].every(element => {
    const tile = element.parentElement;
    const sourceWidth = element.tagName === 'IMG' ? element.naturalWidth : element.videoWidth;
    const sourceHeight = element.tagName === 'IMG' ? element.naturalHeight : element.videoHeight;
    return element.dataset.effectiveFit === window.playback.mediaFit('cover', sourceWidth, sourceHeight, tile.clientWidth, tile.clientHeight);
  }));
  assert.equal(await gridOutput.locator('.grid-tile img,.grid-tile video').evaluateAll(elements => elements.every(element => {
    const tile = element.parentElement;
    const sourceWidth = element.tagName === 'IMG' ? element.naturalWidth : element.videoWidth;
    const sourceHeight = element.tagName === 'IMG' ? element.naturalHeight : element.videoHeight;
    return element.dataset.effectiveFit === window.playback.mediaFit('cover', sourceWidth, sourceHeight, tile.clientWidth, tile.clientHeight);
  })), true);
  assert.equal(await gridOutput.locator('.grid-tile[data-soft-fill="true"]').evaluateAll(tiles => tiles.every(tile => getComputedStyle(tile, '::before').backgroundImage !== 'none')), true);
  await gridOutput.screenshot({ path: path.join(root, 'artifacts/loop-grid-balanced-output.png') });
  await gridOutput.evaluate(() => window.__testGridLayout(4));
  await gridOutput.waitForFunction(() => document.querySelectorAll('.grid-tile[data-active="true"]').length === 4);
  await gridOutput.waitForTimeout(1400);
  assert.equal(await gridOutput.locator('.grid-tile[data-active="false"]').count(), 2);
  assert.ok(await gridOutput.locator('.grid-tile[data-active="true"]').evaluateAll(tiles => {
    const stage = document.querySelector('#stage').getBoundingClientRect();
    const covered = tiles.reduce((total, tile) => { const box = tile.getBoundingClientRect(); return total + box.width * box.height; }, 0);
    return covered / (stage.width * stage.height) > .93;
  }));
  await gridOutput.evaluate(() => window.__testGridLayout(6));
  await gridOutput.waitForFunction(() => document.querySelectorAll('.grid-tile[data-active="true"]').length === 6);
  await gridOutput.waitForTimeout(1400);
  await loop.locator('#fit').selectOption('contain');
  assert.equal(await gridOutput.locator('.grid-tile').evaluateAll(tiles => {
    const bounds = tiles.map(tile => tile.getBoundingClientRect());
    return bounds.every((box, index) => bounds.every((other, otherIndex) => index === otherIndex || box.right <= other.left || other.right <= box.left || box.bottom <= other.top || other.bottom <= box.top));
  }), true);
  assert.ok(await gridOutput.locator('.grid-tile').evaluateAll(tiles => {
    const stage = document.querySelector('#stage').getBoundingClientRect();
    const covered = tiles.reduce((total, tile) => { const box = tile.getBoundingClientRect(); return total + box.width * box.height; }, 0);
    return covered / (stage.width * stage.height) > .93;
  }));
  const initialGrid = await gridOutput.locator('.grid-tile').evaluateAll(tiles => tiles.map(tile => ({ tag: tile.firstElementChild.tagName, identity: `${tile.firstElementChild.tagName}:${tile.firstElementChild.src}` })));
  const videoIndex = initialGrid.findIndex(item => item.tag === 'VIDEO');
  const photoIndex = initialGrid.findIndex(item => item.tag === 'IMG');
  assert.ok(videoIndex >= 0 && photoIndex >= 0);
  await loop.locator('#pause').click(); await loop.waitForFunction(() => document.querySelector('#pause').textContent === 'Pause');
  await gridOutput.waitForFunction(index => document.querySelectorAll('.grid-tile')[index].firstElementChild.currentTime > 0.1, videoIndex);
  assert.equal(await gridOutput.locator('#metadata-readout').isHidden(), true);
  assert.ok(await gridOutput.locator('.grid-readout:not([hidden])').count() > 0);
  assert.match(await gridOutput.locator('.grid-readout:not([hidden])').first().innerText(), /August 2014/);
  assert.doesNotMatch(await gridOutput.locator('.grid-readout:not([hidden])').first().innerText(), /Canon EOS RP/);
  await gridOutput.screenshot({ path: path.join(root, 'artifacts/loop-grid-output.png') });
  await loop.locator('#blackout').click(); assert.equal(await gridOutput.locator('#curtain').isVisible(), true); await loop.locator('#blackout').click();
  await loop.locator('#stop').click(); await loop.waitForFunction(() => document.querySelector('#stop').disabled);
  await loop.locator('#playback-layout').selectOption('single');
  const outputPromise = app.waitForEvent('window'); await loop.locator('#start').click(); const output = await outputPromise;
  await output.waitForSelector('#stage img');
  // Pause freezes the photo; blackout also freezes and hides the output.
  await loop.locator('#pause').click(); await loop.waitForFunction(() => document.querySelector('#pause').textContent === 'Resume');
  assert.match(await output.locator('#metadata-readout').innerText(), /August 2014/);
  assert.match(await output.locator('#metadata-readout').innerText(), /Edinburgh, United Kingdom/);
  assert.doesNotMatch(await output.locator('#metadata-readout').innerText(), /Canon EOS RP/);
  assert.doesNotMatch(await loop.locator('#preview .metadata-readout').innerText(), /Canon EOS RP/);
  await loop.locator('#gps').uncheck(); await output.waitForFunction(() => !document.querySelector('#metadata-readout').textContent.includes('Edinburgh'));
  await loop.locator('#metadata-corner').selectOption('left'); await output.waitForFunction(() => document.querySelector('#metadata-readout').dataset.corner === 'left');
  await loop.locator('#metadata').uncheck(); await output.waitForFunction(() => document.querySelector('#metadata-readout').hidden);
  await loop.locator('#metadata').check(); await output.waitForFunction(() => !document.querySelector('#metadata-readout').hidden);
  await output.screenshot({ path: path.join(root, 'artifacts/loop-metadata-output.png') });
  await new Promise(r => setTimeout(r, 2400)); assert.equal(await output.locator('#stage img').count(), 1);
  await loop.locator('#blackout').click(); assert.equal(await output.locator('#curtain').isVisible(), true);
  await loop.locator('#blackout').click(); await loop.locator('#pause').click();
  await output.waitForSelector('#stage video', { timeout: 15000 });
  assert.equal(await output.locator('#metadata-readout').isVisible(), false);
  await output.waitForFunction(() => document.querySelector('video')?.currentTime > 0.1);
  await loop.locator('#next').click(); await output.waitForSelector('#stage img');
  await loop.locator('#stop').click(); await loop.waitForFunction(() => document.querySelector('#stop').disabled);
  // Reorder and remove persist over restart without deleting imported source media.
  await loop.locator('#playlist li').nth(1).locator('[data-move="-1"]').click();
  await loop.waitForFunction(() => document.querySelector('#playlist .name').textContent === 'loop-test.webm');
  const firstName = await loop.locator('#playlist li').first().locator('.name').textContent(); assert.equal(firstName, 'loop-test.webm');
  await app.close(); app = null;
  const reopened = await launch('loop'); assert.equal(await reopened.locator('#playlist li').first().locator('.name').textContent(), 'loop-test.webm');
  assert.equal(await reopened.locator('#gps').isChecked(), false); assert.equal(await reopened.locator('#metadata-corner').inputValue(), 'left');
  await app.close(); app = null;
  console.log('PASS: photo-only booth, cancellation, recovery, projection video playback, pause, blackout, next and playlist persistence.');
  console.log('Test data:', data);
  await fs.writeFile(path.join(root, 'artifacts/test-result.json'), JSON.stringify({ date: new Date().toISOString(), passed: true, data, photo: savedPhotos.metadata }, null, 2));
})().catch(async e => { console.error(e); if (app) { const windows = app.windows(); if (windows[0]) await windows[0].screenshot({ path: path.join(root, 'artifacts/failure.png') }).catch(() => {}); await app.close().catch(() => {}); } process.exitCode = 1; });
